export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

export const SEND_SOCKET_PING = 'SEND_SOCKET_PING';
export const RECEIVE_SOCKET_PONG = 'RECEIVE_SOCKET_PONG';
export const SEND_SOCKET_LOGIN = 'SEND_SOCKET_LOGIN';

export const TABLES_SUBSCRIBE = 'TABLES_SUBSCRIBE';
export const TABLES_LOAD = 'TABLES_LOAD';
export const TABLE_ADDED = 'TABLE_ADDED';
export const TABLE_REMOVE = 'TABLE_REMOVE';
export const TABLE_HIDE = 'TABLE_HIDE';
export const TABLE_REMOVE_FAILED = 'TABLE_REMOVE_FAILED';
export const TABLE_REMOVED = 'TABLE_REMOVED';
export const TABLE_UPDATED = 'TABLE_UPDATED';
export const MOVE_SCROLL_RIGHT='MOVE_SCROLL_RIGHT';
export const MOVE_SCROLL_LEFT='MOVE_SCROLL_LEFT';

export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR';
export const LOG_OUT = 'LOG_OUT';